import type {
  JobKind,
  JobProgress,
  JobRecord,
  MediaDetectionResult,
  MediaKind,
  Result,
  SubtitleCue,
  TranscriptSegment
} from "./domain";

export const NATIVE_HOST_NAME = "com.subtitler.native_host";
export const NATIVE_PROTOCOL_VERSION = 1 as const;
const MAX_TRANSCRIPT_SEGMENT_RESPONSE_BYTES = 128 * 1024;
const MAX_SUBTITLE_CUE_RESPONSE_BYTES = 128 * 1024;

/** V1 export formats; no user-provided filename or arbitrary extension is accepted. */
export type TranscriptExportFormat = "txt" | "timestamped_txt" | "srt" | "vtt" | "json";

export type PopupRequest =
  | { type: "popup.detect-media" }
  | { type: "popup.get-jobs" }
  /**
   * Retrieves an in-memory, bounded page from a completed transcript. The
   * popup never receives persisted transcript content or a source location.
   */
  | { type: "popup.get-transcript"; jobId: string; cursor?: number; limit?: number }
  /** Explicit user action only: begin one fixed-name browser download. */
  | { type: "popup.export-transcript"; jobId: string; format: TranscriptExportFormat }
  /**
   * Ephemeral connection state only. This is intentionally not backed by
   * chrome.storage: an engine reconnect must establish a fresh advisory.
   */
  | { type: "popup.get-engine-state" }
  | { type: "popup.start-job"; jobKind: JobKind; pastedUrl?: string; forceGenerate?: boolean }
  | { type: "popup.stop-job"; jobId: string };

export interface EngineConnectionState {
  connected: boolean;
  /** True only when both local ASR and FFmpeg are available in this connection. */
  localProcessingAvailable: boolean;
  /** A coarse, non-sensitive recommendation from the currently connected host. */
  localProcessingAdvisory?: NativeLocalProcessingAdvisory;
}

/**
 * A background-to-popup event. It contains only the validated, coarse
 * advisory; raw hardware details, paths, media URLs, and provider state are
 * intentionally absent.
 */
export interface EngineConnectionStateUpdate {
  type: "engine.connection-state";
  payload: EngineConnectionState;
}

export interface PopupTranscriptPage {
  jobId: string;
  segments: TranscriptSegment[];
  nextCursor?: number;
}

/** Contains no content, source path, Blob URL, or browser-selected save path. */
export interface PopupExportStarted {
  downloadId: number;
  filename: "Transcript.txt" | "Transcript-timestamped.txt" | "Subtitles.srt" | "Subtitles.vtt" | "Transcript.json";
}

export type PopupResponse = Result<
  MediaDetectionResult | JobRecord[] | JobRecord | EngineConnectionState | PopupTranscriptPage | PopupExportStarted
>;

export type ContentRequest =
  | { type: "content.get-media" }
  /**
   * Page-local discovery of already requested direct media files. Candidates
   * are bounded and transient; no cookie, request headers, or body bytes are
   * returned to the extension.
   */
  | { type: "content.get-network-media-candidates" }
  | {
      type: "content.start-overlay";
      mediaId: string;
      mode: "existing" | "generated";
      cues?: SubtitleCue[];
      /** Page-local fallback for currently rendered YouTube captions only. */
      visibleCaptionFallback?: boolean;
    }
  | { type: "content.set-overlay-cues"; mediaId: string; cues: SubtitleCue[] }
  | { type: "content.append-overlay-cues"; mediaId: string; cues: SubtitleCue[] }
  /** Begin low-rate playback observation for the active generated overlay. */
  | { type: "content.start-playback-observation"; mediaId: string; jobId: string }
  /** Stop page-local playback observation. No media data is retained. */
  | { type: "content.stop-playback-observation"; mediaId?: string; jobId?: string }
  | { type: "content.stop-overlay"; mediaId?: string };

export type ContentResponse = Result<
  | MediaDetectionResult
  | { mediaUrls: string[] }
  | { started: true }
  | { stopped: true }
  | { observing: true }
  | { observing: false }
>;

/**
 * Page-local playback metadata. This intentionally excludes cue text, media
 * URLs, cookies, and any audio/video data. It is forwarded only while the
 * matching generated-subtitle job is active, and never persisted.
 */
export interface ContentPlaybackUpdate {
  type: "content.playback-update";
  /** Extension-local correlation only; it is never sent to storage or pages. */
  jobId: string;
  mediaId: string;
  positionMs: number;
  playbackRateMilli: number;
  isPaused: boolean;
  seekGeneration: number;
}

export interface NativeStartJobPayload {
  /** Correlation ID generated by the extension; it is not a native authority. */
  jobId: string;
  jobKind: JobKind;
  /**
   * A transient source location. The direct route has no browser credentials;
   * the local route is admitted only after the background verifies a safe
   * active `file:` tab. Neither value is persisted by the extension.
   */
  source: NativeStartSource;
  forceGenerateWithSubtitler?: boolean;
  /**
   * A single, bounded player snapshot for a generated subtitle job. It is
   * delivered with Start so the native scheduler does not need to first lease
   * a zero-time window before the content observer attaches.
   */
  initialPlayback?: {
    positionSeconds: number;
    isPaused: boolean;
  };
}

export type NativeStartSource =
  | {
      /** A recognized recording page resolved locally by the native engine. */
      kind: "page";
      pageUrl: string;
      mediaKind: MediaKind;
      durationSeconds?: number;
    }
  | {
      kind: "direct_url";
      mediaUrl: string;
      mediaKind: MediaKind;
      durationSeconds?: number;
    }
  | {
      kind: "local_file";
      path: string;
      mediaKind: MediaKind;
      durationSeconds?: number;
    };

/**
 * The Phase 2 wire format intentionally mirrors `subtitler-core::protocol`.
 * It is snake_case because serde is the source of truth for the stdio native
 * host; browser-facing UI messages remain TypeScript-friendly elsewhere.
 */
export interface NativeHandshakeRequest {
  request_id: string;
  command: "handshake";
  protocol_version: typeof NATIVE_PROTOCOL_VERSION;
  extension_version: string;
}

export interface NativeStartRequest {
  request_id: string;
  command: "start";
  job: {
    client_job_id: string;
    kind: "full_transcript" | "subtitle_generation";
    media: {
      source:
        | {
            kind: "page";
            page_url: string;
          }
        | {
            kind: "direct_url";
            media_url: string;
          }
        | {
            kind: "local_file";
            path: string;
          };
      hints: {
        duration_ms?: number;
      };
    };
      settings: {
        force_generate_with_subtitler: boolean;
        processing_preference: "local_only";
        speaker_diarization: boolean;
        initial_playback?: {
          position_ms: number;
          playback_rate_milli: number;
          is_paused: boolean;
        };
      };
  };
}

export interface NativeCancelRequest {
  request_id: string;
  command: "cancel";
  job_id: string;
}

export interface NativeStatusRequest {
  request_id: string;
  command: "status";
  job_id: string;
}

/** Reattaches a persisted extension job to its opaque private native result. */
export interface NativeRestoreRequest {
  request_id: string;
  command: "restore";
  job_id: string;
  kind: "full_transcript" | "subtitle_generation";
}

/**
 * Retrieves a bounded page of completed, generated subtitle cues. The cursor
 * is a native-owned offset; the extension only follows cursors returned by the
 * host and keeps cue text in memory rather than chrome.storage.
 */
export interface NativeGetSubtitleCuesRequest {
  request_id: string;
  command: "get_subtitle_cues";
  job_id: string;
  cursor?: number;
  limit?: number;
}

/**
 * Retrieves a bounded page of transcript segments only after a full
 * transcript job has completed. It is deliberately distinct from subtitle
 * cues because a transcript segment is readable text, not overlay layout.
 */
export interface NativeGetTranscriptSegmentsRequest {
  request_id: string;
  command: "get_transcript_segments";
  job_id: string;
  cursor?: number;
  limit?: number;
}

/**
 * Lossy, rate-limited playback state used by the native scheduler to decide
 * which subtitle window to prioritize. The native protocol remains snake_case.
 */
export interface NativePlaybackUpdateRequest {
  request_id: string;
  command: "playback_update";
  job_id: string;
  position_ms: number;
  playback_rate_milli: number;
  is_paused: boolean;
  seek_generation: number;
}

export interface PlaybackUpdateSnapshot {
  positionMs: number;
  playbackRateMilli: number;
  isPaused: boolean;
  seekGeneration: number;
}

export type NativeRequest =
  | NativeHandshakeRequest
  | NativeStartRequest
  | NativeCancelRequest
  | NativeStatusRequest
  | NativeRestoreRequest
  | NativeGetSubtitleCuesRequest
  | NativeGetTranscriptSegmentsRequest
  | NativePlaybackUpdateRequest;

interface NativeHostJobStatus {
  job_id: string;
  kind: "full_transcript" | "subtitle_generation";
  state: "queued" | "discovering" | "acquiring" | "processing" | "completed" | "cancelled" | "stale" | "failed";
  progress: {
    media_duration_ms?: number;
    processed_ms: number;
    subtitle_buffer_ahead_ms?: number;
    phase?: "resolving" | "acquiring" | "decoding" | "transcribing" | "segmenting" | "finalizing" | "complete" | "failed" | "cancelled" | "stale";
    last_progress_at_ms?: number;
    media_bytes_processed?: number;
    audio_seconds_decoded_ms?: number;
    audio_seconds_transcribed_ms?: number;
    completed_intervals?: number;
    worker_pid?: number;
    worker_status?: "not_started" | "active" | "waiting" | "finished" | "unavailable";
  };
  message?: string;
  failure?: {
    code: string;
    message: string;
    retryable: boolean;
  };
}

export type NativeLocalProcessingSelectionSource = "automatic" | "advanced_environment";
export type NativeLocalProcessingModel = "tiny" | "base" | "small" | "medium" | "large_v3_turbo";
export type NativeLocalProcessingQuantization = "q5_0" | "q5_k_m" | "q8_0" | "f16";
export type NativeLocalProcessingBackend = "cpu" | "cuda" | "metal" | "vulkan";
export type NativeLocalProcessingPerformance = "excellent" | "good" | "may_be_slow" | "cloud_helpful";

/**
 * The only processing-plan data the extension admits from a native handshake.
 * It deliberately excludes device names, memory totals, operating-system
 * data, local paths, URLs, credentials, and provider configuration.
 */
export interface NativeLocalProcessingAdvisory {
  selectionSource: NativeLocalProcessingSelectionSource;
  model: NativeLocalProcessingModel;
  quantization: NativeLocalProcessingQuantization;
  backend: NativeLocalProcessingBackend;
  localPerformance: NativeLocalProcessingPerformance;
}

interface NativeCapabilities {
  protocol_version: typeof NATIVE_PROTOCOL_VERSION;
  local_asr_available: boolean;
  ffmpeg_available: boolean;
  direct_media_acquisition: boolean;
  browser_mediated_acquisition: boolean;
  cloud_processing_requires_explicit_approval: boolean;
  /** Optional to preserve compatibility with an already-installed V1 host. */
  localProcessingAdvisory?: NativeLocalProcessingAdvisory;
}

/** Exact cue shape emitted by the Rust `subtitle_cues` response. */
export interface NativeSubtitleCue {
  timing: {
    start_ms: number;
    end_ms: number;
  };
  lines: string[];
  speaker?: string;
}

/** Exact segment shape emitted by the Rust `transcript_segments` response. */
export interface NativeTranscriptSegment {
  timing: {
    start_ms: number;
    end_ms: number;
  };
  text: string;
  speaker?: string;
}

export type NativeHostResponse =
  | {
      request_id?: string;
      response: "handshake";
      native_host_name: string;
      protocol_version: typeof NATIVE_PROTOCOL_VERSION;
      native_version: string;
      capabilities: NativeCapabilities;
    }
  | { request_id?: string; response: "job_started"; job: NativeHostJobStatus }
  | { request_id?: string; response: "job_cancelled"; job: NativeHostJobStatus }
  | { request_id?: string; response: "job_status"; job: NativeHostJobStatus }
  | { request_id?: string; response: "job_restored"; job: NativeHostJobStatus }
  | {
      request_id?: string;
      response: "subtitle_cues";
      job_id: string;
      cues: NativeSubtitleCue[];
      next_cursor?: number;
    }
  | {
      request_id?: string;
      response: "transcript_segments";
      job_id: string;
      segments: NativeTranscriptSegment[];
      next_cursor?: number;
    }
  | { request_id?: string; response: "error"; code: string; message: string; retryable: boolean };

export type NativeInboundMessage =
  | {
      protocolVersion: typeof NATIVE_PROTOCOL_VERSION;
      type: "engine.ready";
      payload: {
        engineVersion: string;
        /** True only when this host can actually run local ASR and FFmpeg. */
        localProcessingAvailable: boolean;
        localProcessingAdvisory?: NativeLocalProcessingAdvisory;
      };
    }
  | {
      protocolVersion: typeof NATIVE_PROTOCOL_VERSION;
      type: "job.accepted";
      payload: { jobId: string; nativeJobId: string };
    }
  | {
      protocolVersion: typeof NATIVE_PROTOCOL_VERSION;
      type: "job.progress";
      payload: { jobId: string; status: "processing" | "buffering"; progress: JobProgress };
    }
  | {
      protocolVersion: typeof NATIVE_PROTOCOL_VERSION;
      type: "job.subtitle-cues";
      payload: { jobId: string; cues: SubtitleCue[] };
    }
  | {
      protocolVersion: typeof NATIVE_PROTOCOL_VERSION;
      type: "job.transcript-segments";
      payload: { jobId: string; segments: TranscriptSegment[] };
    }
  | {
      protocolVersion: typeof NATIVE_PROTOCOL_VERSION;
      type: "job.transcript-cues";
      payload: { jobId: string; cues: SubtitleCue[] };
    }
  | {
      protocolVersion: typeof NATIVE_PROTOCOL_VERSION;
      type: "job.completed";
      payload: { jobId: string };
    }
  | {
      protocolVersion: typeof NATIVE_PROTOCOL_VERSION;
      type: "job.cancelled";
      payload: { jobId: string };
    }
  | {
      protocolVersion: typeof NATIVE_PROTOCOL_VERSION;
      type: "job.stale";
      payload: { jobId: string; message: string };
    }
  | {
      protocolVersion: typeof NATIVE_PROTOCOL_VERSION;
      type: "job.failed";
      payload: {
        jobId: string;
        code: "UNSUPPORTED_MEDIA" | "PROTECTED_MEDIA" | "NATIVE_ERROR";
        message: string;
        retryable: boolean;
      };
    };

export function isPopupRequest(value: unknown): value is PopupRequest {
  if (!isRecord(value) || typeof value.type !== "string") {
    return false;
  }
  switch (value.type) {
    case "popup.detect-media":
    case "popup.get-jobs":
    case "popup.get-engine-state":
      return true;
    case "popup.get-transcript":
      return (
        typeof value.jobId === "string" &&
        value.jobId.length > 0 &&
        value.jobId.length <= 256 &&
        (value.cursor === undefined || isNativeCursor(value.cursor)) &&
        (value.limit === undefined || isTranscriptSegmentPageLimit(value.limit))
      );
    case "popup.export-transcript":
      return (
        typeof value.jobId === "string" &&
        value.jobId.length > 0 &&
        value.jobId.length <= 256 &&
        isTranscriptExportFormat(value.format)
      );
    case "popup.stop-job":
      return typeof value.jobId === "string" && value.jobId.length > 0;
    case "popup.start-job":
      return (
        (value.jobKind === "subtitle" || value.jobKind === "transcript") &&
        (value.pastedUrl === undefined || typeof value.pastedUrl === "string") &&
        (value.forceGenerate === undefined || typeof value.forceGenerate === "boolean")
      );
    default:
      return false;
  }
}

export function parseEngineConnectionStateUpdate(value: unknown): EngineConnectionStateUpdate | null {
  if (!isRecord(value) || value.type !== "engine.connection-state") {
    return null;
  }
  const payload = parseEngineConnectionState(value.payload);
  return payload ? { type: "engine.connection-state", payload } : null;
}

export function isEngineConnectionStateUpdate(value: unknown): value is EngineConnectionStateUpdate {
  return parseEngineConnectionStateUpdate(value) !== null;
}

export function isContentRequest(value: unknown): value is ContentRequest {
  if (!isRecord(value) || typeof value.type !== "string") {
    return false;
  }
  switch (value.type) {
    case "content.get-media":
    case "content.get-network-media-candidates":
      return true;
    case "content.start-overlay":
      return (
        typeof value.mediaId === "string" &&
        (value.mode === "existing" || value.mode === "generated") &&
        (value.cues === undefined || isSubtitleCueArray(value.cues)) &&
        (value.visibleCaptionFallback === undefined || typeof value.visibleCaptionFallback === "boolean")
      );
    case "content.set-overlay-cues":
      return typeof value.mediaId === "string" && isSubtitleCueArray(value.cues);
    case "content.append-overlay-cues":
      return typeof value.mediaId === "string" && isSubtitleCueArray(value.cues, 200);
    case "content.start-playback-observation":
      return typeof value.mediaId === "string" && value.mediaId.length > 0 && isNativeJobId(value.jobId);
    case "content.stop-playback-observation":
      return (
        (value.mediaId === undefined || typeof value.mediaId === "string") &&
        (value.jobId === undefined || isNativeJobId(value.jobId))
      );
    case "content.stop-overlay":
      return value.mediaId === undefined || typeof value.mediaId === "string";
    default:
      return false;
  }
}

export function isContentPlaybackUpdate(value: unknown): value is ContentPlaybackUpdate {
  return (
    isRecord(value) &&
    value.type === "content.playback-update" &&
    isNativeJobId(value.jobId) &&
    typeof value.mediaId === "string" &&
    value.mediaId.length > 0 &&
    isPlaybackPositionMs(value.positionMs) &&
    isPlaybackRateMilli(value.playbackRateMilli) &&
    typeof value.isPaused === "boolean" &&
    isSeekGeneration(value.seekGeneration)
  );
}

/** Only direct HTTPS URLs are valid native input. Reject data/blob/file URLs and embedded credentials. */
export function sanitizeDirectMediaUrl(value: unknown): string | null {
  if (typeof value !== "string" || value.length > 16_384) {
    return null;
  }
  try {
    const url = new URL(value);
    if (url.protocol !== "https:" || url.username || url.password) {
      return null;
    }
    url.hash = "";
    return url.href;
  } catch {
    return null;
  }
}

/**
 * Converts a safe local file URL into an absolute native filesystem path.
 * Remote/UNC authorities, ambiguous double-slash paths, queries, controls,
 * and non-absolute paths are rejected. A fragment is intentionally ignored:
 * it is not part of the filesystem path.
 */
export function sanitizeLocalFileUrl(value: unknown): string | null {
  if (typeof value !== "string" || value.length === 0 || value.length > 16_384) {
    return null;
  }
  try {
    const url = new URL(value);
    if (url.protocol !== "file:" || url.host !== "" || url.search !== "") {
      return null;
    }
    // A double-slash pathname can be interpreted as a network/UNC location on
    // Windows even when URL parsing did not expose an authority component.
    if (url.pathname.startsWith("//") || /%2f|%5c/i.test(url.pathname)) {
      return null;
    }
    const pathname = decodeURIComponent(url.pathname);
    if (pathname.startsWith("//")) {
      return null;
    }
    const windowsPath = /^\/([a-z]):\/(.*)$/i.exec(pathname);
    const path = windowsPath ? `${windowsPath[1] ?? ""}:\\${(windowsPath[2] ?? "").replaceAll("/", "\\")}` : pathname;
    return sanitizeLocalFilePath(path);
  } catch {
    return null;
  }
}

/** True only for a safe, local non-UNC file document URL. */
export function isSafeLocalFilePageUrl(value: unknown): boolean {
  return sanitizeLocalFileUrl(value) !== null;
}

/**
 * Validates an already-decoded local path before native-message serialization.
 * It deliberately accepts only absolute POSIX paths or drive-rooted Windows
 * paths and never accepts UNC/device paths.
 */
export function sanitizeLocalFilePath(value: unknown): string | null {
  if (typeof value !== "string" || value.length === 0 || value.length > 32_768) {
    return null;
  }
  if (/[\x00-\x1f\x7f]/.test(value) || value.trim().length === 0) {
    return null;
  }
  if (value.startsWith("\\\\") || value.startsWith("//")) {
    return null;
  }
  const isDriveRootedWindowsPath = /^[a-z]:[\\/]/i.test(value);
  const isPosixAbsolutePath = value.startsWith("/") && !value.startsWith("//");
  return isDriveRootedWindowsPath || isPosixAbsolutePath ? value : null;
}

export function createNativeHandshakeRequest(requestId = createRequestId()): NativeHandshakeRequest {
  return {
    request_id: requireNativeRequestId(requestId),
    command: "handshake",
    protocol_version: NATIVE_PROTOCOL_VERSION,
    extension_version: "0.1.0"
  };
}

export function createNativeStartRequest(
  payload: NativeStartJobPayload,
  requestId = createRequestId()
): NativeStartRequest {
  const hints: { duration_ms?: number } = {};
  if (payload.source.durationSeconds !== undefined) {
    hints.duration_ms = Math.max(0, Math.round(payload.source.durationSeconds * 1_000));
  }
  const source = nativeSourceFromStartPayload(payload.source);
  const settings: NativeStartRequest["job"]["settings"] = {
    force_generate_with_subtitler: payload.forceGenerateWithSubtitler === true,
    processing_preference: "local_only",
    speaker_diarization: false
  };
  if (payload.jobKind === "subtitle" && payload.initialPlayback) {
    settings.initial_playback = {
      position_ms: requirePlaybackPositionMs(Math.round(payload.initialPlayback.positionSeconds * 1_000)),
      playback_rate_milli: 1_000,
      is_paused: requireBoolean(payload.initialPlayback.isPaused, "initial playback paused state")
    };
  }
  return {
    request_id: requireNativeRequestId(requestId),
    command: "start",
    job: {
      client_job_id: payload.jobId,
      kind: payload.jobKind === "transcript" ? "full_transcript" : "subtitle_generation",
      media: {
        source,
        hints
      },
      settings
    }
  };
}

function nativeSourceFromStartPayload(source: NativeStartSource): NativeStartRequest["job"]["media"]["source"] {
  if (source.kind === "page") {
    const pageUrl = sanitizeDirectMediaUrl(source.pageUrl);
    if (!pageUrl) {
      throw new Error("invalid recording page URL");
    }
    return { kind: "page", page_url: pageUrl };
  }
  if (source.kind === "direct_url") {
    const mediaUrl = sanitizeDirectMediaUrl(source.mediaUrl);
    if (!mediaUrl) {
      throw new Error("invalid direct media URL");
    }
    return { kind: "direct_url", media_url: mediaUrl };
  }
  const path = sanitizeLocalFilePath(source.path);
  if (!path) {
    throw new Error("invalid local media path");
  }
  return { kind: "local_file", path };
}

export function createNativeCancelRequest(jobId: string, requestId = createRequestId()): NativeCancelRequest {
  return { request_id: requireNativeRequestId(requestId), command: "cancel", job_id: requireNativeJobId(jobId) };
}

export function createNativeStatusRequest(jobId: string, requestId = createRequestId()): NativeStatusRequest {
  return { request_id: requireNativeRequestId(requestId), command: "status", job_id: requireNativeJobId(jobId) };
}

export function createNativeRestoreRequest(
  jobId: string,
  kind: "transcript" | "subtitle",
  requestId = createRequestId()
): NativeRestoreRequest {
  return {
    request_id: requireNativeRequestId(requestId),
    command: "restore",
    job_id: requireNativeJobId(jobId),
    kind: kind === "transcript" ? "full_transcript" : "subtitle_generation"
  };
}

export function createNativeGetSubtitleCuesRequest(
  jobId: string,
  page: { cursor?: number; limit?: number } = {},
  requestId = createRequestId()
): NativeGetSubtitleCuesRequest {
  const request: NativeGetSubtitleCuesRequest = {
    request_id: requireNativeRequestId(requestId),
    command: "get_subtitle_cues",
    job_id: requireNativeJobId(jobId)
  };
  if (page.cursor !== undefined) {
    request.cursor = requireNativeCursor(page.cursor);
  }
  if (page.limit !== undefined) {
    request.limit = requireSubtitleCuePageLimit(page.limit);
  }
  return request;
}

export function createNativeGetTranscriptSegmentsRequest(
  jobId: string,
  page: { cursor?: number; limit?: number } = {},
  requestId = createRequestId()
): NativeGetTranscriptSegmentsRequest {
  const request: NativeGetTranscriptSegmentsRequest = {
    request_id: requireNativeRequestId(requestId),
    command: "get_transcript_segments",
    job_id: requireNativeJobId(jobId)
  };
  if (page.cursor !== undefined) {
    request.cursor = requireNativeCursor(page.cursor);
  }
  if (page.limit !== undefined) {
    request.limit = requireTranscriptSegmentPageLimit(page.limit);
  }
  return request;
}

export function createNativePlaybackUpdateRequest(
  jobId: string,
  snapshot: PlaybackUpdateSnapshot,
  requestId = createRequestId()
): NativePlaybackUpdateRequest {
  return {
    request_id: requireNativeRequestId(requestId),
    command: "playback_update",
    job_id: requireNativeJobId(jobId),
    position_ms: requirePlaybackPositionMs(snapshot.positionMs),
    playback_rate_milli: requirePlaybackRateMilli(snapshot.playbackRateMilli),
    is_paused: requireBoolean(snapshot.isPaused, "playback paused state"),
    seek_generation: requireSeekGeneration(snapshot.seekGeneration)
  };
}

/** Validate the exact snake_case response emitted by the Rust native host. */
export function parseNativeHostResponse(value: unknown): NativeHostResponse | null {
  if (!isRecord(value) || typeof value.response !== "string") {
    return null;
  }
  if (value.request_id !== undefined && !isNativeRequestId(value.request_id)) {
    return null;
  }
  const requestId = value.request_id;
  switch (value.response) {
    case "handshake": {
      const capabilities = parseCapabilities(value.capabilities);
      if (
        value.protocol_version !== NATIVE_PROTOCOL_VERSION ||
        typeof value.native_host_name !== "string" ||
        typeof value.native_version !== "string" ||
        !capabilities
      ) {
        return null;
      }
      return withRequestId(requestId, {
        response: "handshake" as const,
        native_host_name: value.native_host_name,
        protocol_version: NATIVE_PROTOCOL_VERSION,
        native_version: value.native_version,
        capabilities
      });
    }
    case "job_started": {
      const job = parseNativeJobStatus(value.job);
      return job ? withRequestId(requestId, { response: "job_started" as const, job }) : null;
    }
    case "job_cancelled": {
      const job = parseNativeJobStatus(value.job);
      return job ? withRequestId(requestId, { response: "job_cancelled" as const, job }) : null;
    }
    case "job_status": {
      const job = parseNativeJobStatus(value.job);
      return job ? withRequestId(requestId, { response: "job_status" as const, job }) : null;
    }
    case "job_restored": {
      const job = parseNativeJobStatus(value.job);
      return job ? withRequestId(requestId, { response: "job_restored" as const, job }) : null;
    }
    case "subtitle_cues": {
      const cues = parseNativeSubtitleCues(value.cues);
      const nextCursor = value.next_cursor;
      if (
        !isNativeJobId(value.job_id) ||
        !cues ||
        (nextCursor !== undefined && nextCursor !== null && !isNativeCursor(nextCursor)) ||
        !isBoundedSubtitleCueResponse(requestId, value.job_id, cues, typeof nextCursor === "number" ? nextCursor : undefined)
      ) {
        return null;
      }
      const response: Extract<NativeHostResponse, { response: "subtitle_cues" }> = {
        response: "subtitle_cues",
        job_id: value.job_id,
        cues
      };
      if (typeof nextCursor === "number") {
        response.next_cursor = nextCursor;
      }
      return withRequestId(requestId, response);
    }
    case "transcript_segments": {
      const segments = parseNativeTranscriptSegments(value.segments);
      const nextCursor = value.next_cursor;
      if (
        !isNativeJobId(value.job_id) ||
        !segments ||
        (nextCursor !== undefined && nextCursor !== null && !isNativeCursor(nextCursor)) ||
        !isBoundedTranscriptSegmentResponse(requestId, value.job_id, segments, typeof nextCursor === "number" ? nextCursor : undefined)
      ) {
        return null;
      }
      const response: Extract<NativeHostResponse, { response: "transcript_segments" }> = {
        response: "transcript_segments",
        job_id: value.job_id,
        segments
      };
      if (typeof nextCursor === "number") {
        response.next_cursor = nextCursor;
      }
      return withRequestId(requestId, response);
    }
    case "error":
      return typeof value.code === "string" && typeof value.message === "string" && value.message.length <= 8_000 && typeof value.retryable === "boolean"
        ? withRequestId(requestId, { response: "error" as const, code: value.code, message: value.message, retryable: value.retryable })
        : null;
    default:
      return null;
  }
}

function parseCapabilities(value: unknown): NativeCapabilities | null {
  if (!isRecord(value) || value.protocol_version !== NATIVE_PROTOCOL_VERSION) {
    return null;
  }
  const flags = [
    "local_asr_available",
    "ffmpeg_available",
    "direct_media_acquisition",
    "browser_mediated_acquisition",
    "cloud_processing_requires_explicit_approval"
  ] as const;
  if (flags.some((flag) => typeof value[flag] !== "boolean")) {
    return null;
  }
  const capabilities: NativeCapabilities = {
    protocol_version: NATIVE_PROTOCOL_VERSION,
    local_asr_available: value.local_asr_available as boolean,
    ffmpeg_available: value.ffmpeg_available as boolean,
    direct_media_acquisition: value.direct_media_acquisition as boolean,
    browser_mediated_acquisition: value.browser_mediated_acquisition as boolean,
    cloud_processing_requires_explicit_approval: value.cloud_processing_requires_explicit_approval as boolean
  };
  // Advisory support is additive. An older host omits it, while a malformed
  // optional value is discarded rather than becoming extension state.
  const advisory = parseNativeLocalProcessingAdvisory(value.local_processing_advisory);
  if (advisory) {
    capabilities.localProcessingAdvisory = advisory;
  }
  return capabilities;
}

function parseEngineConnectionState(value: unknown): EngineConnectionState | null {
  if (!isRecord(value) || typeof value.connected !== "boolean" || typeof value.localProcessingAvailable !== "boolean") {
    return null;
  }
  const advisory = parseBrowserLocalProcessingAdvisory(value.localProcessingAdvisory);
  if (value.localProcessingAdvisory !== undefined && !advisory) {
    return null;
  }
  if (!value.connected && (value.localProcessingAvailable || advisory !== undefined)) {
    return null;
  }
  const state: EngineConnectionState = {
    connected: value.connected,
    localProcessingAvailable: value.localProcessingAvailable
  };
  if (advisory) {
    state.localProcessingAdvisory = advisory;
  }
  return state;
}

/**
 * Strictly validates the compact Rust handshake fields. Unknown fields are
 * ignored, but every admitted field must be one of the exact wire enums.
 */
function parseNativeLocalProcessingAdvisory(value: unknown): NativeLocalProcessingAdvisory | undefined {
  if (!isRecord(value)) {
    return undefined;
  }
  if (
    !isOneOf(value.selection_source, ["automatic", "advanced_environment"] as const) ||
    !isOneOf(value.model, ["tiny", "base", "small", "medium", "large_v3_turbo"] as const) ||
    !isOneOf(value.quantization, ["q5_0", "q5_k_m", "q8_0", "f16"] as const) ||
    !isOneOf(value.backend, ["cpu", "cuda", "metal", "vulkan"] as const) ||
    !isOneOf(value.local_performance, ["excellent", "good", "may_be_slow", "cloud_helpful"] as const)
  ) {
    return undefined;
  }
  return {
    selectionSource: value.selection_source,
    model: value.model,
    quantization: value.quantization,
    backend: value.backend,
    localPerformance: value.local_performance
  };
}

function parseBrowserLocalProcessingAdvisory(value: unknown): NativeLocalProcessingAdvisory | undefined {
  if (!isRecord(value)) {
    return undefined;
  }
  if (
    !isOneOf(value.selectionSource, ["automatic", "advanced_environment"] as const) ||
    !isOneOf(value.model, ["tiny", "base", "small", "medium", "large_v3_turbo"] as const) ||
    !isOneOf(value.quantization, ["q5_0", "q5_k_m", "q8_0", "f16"] as const) ||
    !isOneOf(value.backend, ["cpu", "cuda", "metal", "vulkan"] as const) ||
    !isOneOf(value.localPerformance, ["excellent", "good", "may_be_slow", "cloud_helpful"] as const)
  ) {
    return undefined;
  }
  return {
    selectionSource: value.selectionSource,
    model: value.model,
    quantization: value.quantization,
    backend: value.backend,
    localPerformance: value.localPerformance
  };
}

function parseNativeJobStatus(value: unknown): NativeHostJobStatus | null {
  if (!isRecord(value) || !isNativeJobId(value.job_id) || !isRecord(value.progress)) {
    return null;
  }
  const nativeProgress = value.progress;
  const kinds = ["full_transcript", "subtitle_generation"] as const;
  const states = ["queued", "discovering", "acquiring", "processing", "completed", "cancelled", "stale", "failed"] as const;
  if (!kinds.includes(value.kind as (typeof kinds)[number]) || !states.includes(value.state as (typeof states)[number])) {
    return null;
  }
  const processedMs = nativeProgress.processed_ms;
  if (!isNonNegativeNumber(processedMs)) {
    return null;
  }
  const progress: NativeHostJobStatus["progress"] = { processed_ms: processedMs };
  const mediaDurationMs = nativeProgress.media_duration_ms;
  if (isNonNegativeNumber(mediaDurationMs)) {
    progress.media_duration_ms = mediaDurationMs;
  }
  const subtitleBufferAheadMs = nativeProgress.subtitle_buffer_ahead_ms;
  if (isNonNegativeNumber(subtitleBufferAheadMs)) {
    progress.subtitle_buffer_ahead_ms = subtitleBufferAheadMs;
  }
  const phases = ["resolving", "acquiring", "decoding", "transcribing", "segmenting", "finalizing", "complete", "failed", "cancelled", "stale"] as const;
  const phase = nativeProgress.phase;
  if (phases.includes(phase as (typeof phases)[number])) {
    progress.phase = phase as NonNullable<NativeHostJobStatus["progress"]["phase"]>;
  }
  const activityFields = [
    "last_progress_at_ms",
    "media_bytes_processed",
    "audio_seconds_decoded_ms",
    "audio_seconds_transcribed_ms",
    "completed_intervals",
    "worker_pid"
  ] as const;
  // Rust serializes optional telemetry as `null` when it is unavailable (for
  // example a completed job has no live worker PID). Treat null exactly like
  // an omitted optional field; rejecting it would discard the whole terminal
  // response and leave the browser job permanently "Recovering".
  if (
    activityFields.some(
      (field) => nativeProgress[field] !== undefined && nativeProgress[field] !== null && !isNonNegativeInteger(nativeProgress[field])
    )
  ) {
    return null;
  }
  if (isNonNegativeInteger(nativeProgress.last_progress_at_ms)) progress.last_progress_at_ms = nativeProgress.last_progress_at_ms;
  if (isNonNegativeInteger(nativeProgress.media_bytes_processed)) progress.media_bytes_processed = nativeProgress.media_bytes_processed;
  if (isNonNegativeInteger(nativeProgress.audio_seconds_decoded_ms)) progress.audio_seconds_decoded_ms = nativeProgress.audio_seconds_decoded_ms;
  if (isNonNegativeInteger(nativeProgress.audio_seconds_transcribed_ms)) progress.audio_seconds_transcribed_ms = nativeProgress.audio_seconds_transcribed_ms;
  if (isNonNegativeInteger(nativeProgress.completed_intervals)) progress.completed_intervals = nativeProgress.completed_intervals;
  if (isNonNegativeInteger(nativeProgress.worker_pid)) progress.worker_pid = nativeProgress.worker_pid;
  const workerStatuses = ["not_started", "active", "waiting", "finished", "unavailable"] as const;
  if (nativeProgress.worker_status !== undefined) {
    if (!workerStatuses.includes(nativeProgress.worker_status as (typeof workerStatuses)[number])) return null;
    progress.worker_status = nativeProgress.worker_status as NonNullable<NativeHostJobStatus["progress"]["worker_status"]>;
  }
  const status: NativeHostJobStatus = {
    job_id: value.job_id,
    kind: value.kind as NativeHostJobStatus["kind"],
    state: value.state as NativeHostJobStatus["state"],
    progress
  };
  if (typeof value.message === "string" && value.message.length <= 8_000) {
    status.message = value.message;
  }
  const failure = parseNativeJobFailure(value.failure);
  if (failure) {
    status.failure = failure;
  }
  if (status.state === "failed" && !status.failure) {
    return null;
  }
  return status;
}

function parseNativeJobFailure(value: unknown): NativeHostJobStatus["failure"] | undefined {
  if (!isRecord(value)) {
    return undefined;
  }
  if (
    typeof value.code !== "string" ||
    typeof value.message !== "string" ||
    value.message.length > 8_000 ||
    typeof value.retryable !== "boolean"
  ) {
    return undefined;
  }
  return { code: value.code, message: value.message, retryable: value.retryable };
}

function parseNativeSubtitleCues(value: unknown): NativeSubtitleCue[] | null {
  if (!Array.isArray(value) || value.length > 200) {
    return null;
  }
  const cues: NativeSubtitleCue[] = [];
  for (const candidate of value) {
    if (!isRecord(candidate) || !isRecord(candidate.timing) || !Array.isArray(candidate.lines)) {
      return null;
    }
    const { start_ms: startMs, end_ms: endMs } = candidate.timing;
    if (!isNonNegativeInteger(startMs) || !isNonNegativeInteger(endMs) || endMs <= startMs) {
      return null;
    }
    if (
      candidate.lines.length === 0 ||
      candidate.lines.length > 4 ||
      !candidate.lines.every((line) => typeof line === "string" && line.length <= 8_000)
    ) {
      return null;
    }
    if (candidate.speaker !== undefined && candidate.speaker !== null && typeof candidate.speaker !== "string") {
      return null;
    }
    const cue: NativeSubtitleCue = {
      timing: { start_ms: startMs, end_ms: endMs },
      lines: [...candidate.lines]
    };
    if (typeof candidate.speaker === "string") {
      cue.speaker = candidate.speaker;
    }
    cues.push(cue);
  }
  return cues;
}

/**
 * The native host already bounds serialized response bytes. Revalidate the
 * page count, timing, and individual text/speaker sizes before any transcript
 * text enters extension memory.
 */
function parseNativeTranscriptSegments(value: unknown): NativeTranscriptSegment[] | null {
  if (!Array.isArray(value) || value.length > 100) {
    return null;
  }
  const segments: NativeTranscriptSegment[] = [];
  for (const candidate of value) {
    if (!isRecord(candidate) || !isRecord(candidate.timing)) {
      return null;
    }
    const { start_ms: startMs, end_ms: endMs } = candidate.timing;
    if (
      !isNonNegativeInteger(startMs) ||
      !isNonNegativeInteger(endMs) ||
      endMs < startMs ||
      typeof candidate.text !== "string" ||
      candidate.text.length > 16_384 ||
      utf8ByteLength(candidate.text) > 16_384
    ) {
      return null;
    }
    if (
      candidate.speaker !== undefined &&
      candidate.speaker !== null &&
      (typeof candidate.speaker !== "string" || candidate.speaker.length > 512 || utf8ByteLength(candidate.speaker) > 512)
    ) {
      return null;
    }
    const segment: NativeTranscriptSegment = {
      timing: { start_ms: startMs, end_ms: endMs },
      text: candidate.text
    };
    if (typeof candidate.speaker === "string") {
      segment.speaker = candidate.speaker;
    }
    segments.push(segment);
  }
  return segments;
}

function withRequestId<T extends object>(requestId: string | undefined, response: T): T & { request_id?: string } {
  return requestId === undefined ? response : { ...response, request_id: requestId };
}

function isSubtitleCueArray(value: unknown, maximumLength = 2_000): value is SubtitleCue[] {
  return (
    Array.isArray(value) &&
    value.length <= maximumLength &&
    value.every((cue) => {
      if (!isRecord(cue)) {
        return false;
      }
      return (
        typeof cue.id === "string" &&
        typeof cue.text === "string" &&
        cue.text.length <= 8_000 &&
        typeof cue.startSeconds === "number" &&
        Number.isFinite(cue.startSeconds) &&
        cue.startSeconds >= 0 &&
        typeof cue.endSeconds === "number" &&
        Number.isFinite(cue.endSeconds) &&
        cue.endSeconds > cue.startSeconds &&
        (cue.speaker === undefined || typeof cue.speaker === "string")
      );
    })
  );
}

function isNonNegativeNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value) && value >= 0;
}

function isOneOf<const T extends string>(value: unknown, allowed: readonly T[]): value is T {
  return typeof value === "string" && (allowed as readonly string[]).includes(value);
}

function isNonNegativeInteger(value: unknown): value is number {
  return typeof value === "number" && Number.isSafeInteger(value) && value >= 0;
}

function isNativeJobId(value: unknown): value is string {
  return (
    typeof value === "string" &&
    /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)
  );
}

function isNativeRequestId(value: unknown): value is string {
  return typeof value === "string" && value.length > 0 && value.length <= 256;
}

function isNativeCursor(value: unknown): value is number {
  return isNonNegativeInteger(value) && value <= 0xffff_ffff;
}

function isPlaybackPositionMs(value: unknown): value is number {
  return isNonNegativeInteger(value);
}

function isPlaybackRateMilli(value: unknown): value is number {
  return isNonNegativeInteger(value) && value >= 250 && value <= 4_000;
}

function isSeekGeneration(value: unknown): value is number {
  return isNativeCursor(value);
}

function requireNativeJobId(value: string): string {
  if (!isNativeJobId(value)) {
    throw new Error("Subtitler received an invalid local job identifier.");
  }
  return value;
}

function requireNativeRequestId(value: string): string {
  if (!isNativeRequestId(value)) {
    throw new Error("Subtitler received an invalid native request identifier.");
  }
  return value;
}

function requireNativeCursor(value: number): number {
  if (!isNativeCursor(value)) {
    throw new Error("Subtitler received an invalid subtitle-cue cursor.");
  }
  return value;
}

function requireSubtitleCuePageLimit(value: number): number {
  if (!isNonNegativeInteger(value) || value < 1 || value > 200) {
    throw new Error("Subtitler received an invalid subtitle-cue page limit.");
  }
  return value;
}

function isTranscriptSegmentPageLimit(value: unknown): value is number {
  return isNonNegativeInteger(value) && value >= 1 && value <= 100;
}

export function isTranscriptExportFormat(value: unknown): value is TranscriptExportFormat {
  return value === "txt" || value === "timestamped_txt" || value === "srt" || value === "vtt" || value === "json";
}

function requireTranscriptSegmentPageLimit(value: number): number {
  if (!isTranscriptSegmentPageLimit(value)) {
    throw new Error("Subtitler received an invalid transcript-segment page limit.");
  }
  return value;
}

function requirePlaybackPositionMs(value: number): number {
  if (!isPlaybackPositionMs(value)) {
    throw new Error("Subtitler received an invalid playback position.");
  }
  return value;
}

function requirePlaybackRateMilli(value: number): number {
  if (!isPlaybackRateMilli(value)) {
    throw new Error("Subtitler received an invalid playback rate.");
  }
  return value;
}

function requireSeekGeneration(value: number): number {
  if (!isSeekGeneration(value)) {
    throw new Error("Subtitler received an invalid playback seek generation.");
  }
  return value;
}

function requireBoolean(value: boolean, description: string): boolean {
  if (typeof value !== "boolean") {
    throw new Error(`Subtitler received an invalid ${description}.`);
  }
  return value;
}

function createRequestId(): string {
  return crypto.randomUUID();
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function utf8ByteLength(value: string): number {
  return new TextEncoder().encode(value).byteLength;
}

/**
 * Defense in depth for a compromised native host: the Rust implementation
 * caps these responses at 120 KiB, while the extension refuses any equivalent
 * admitted page at or above Chrome native messaging's 128 KiB safety bound.
 */
function isBoundedTranscriptSegmentResponse(
  requestId: string | undefined,
  jobId: string,
  segments: readonly NativeTranscriptSegment[],
  nextCursor: number | undefined
): boolean {
  const response: Record<string, unknown> = {
    response: "transcript_segments",
    job_id: jobId,
    segments
  };
  if (requestId !== undefined) {
    response.request_id = requestId;
  }
  if (nextCursor !== undefined) {
    response.next_cursor = nextCursor;
  }
  return utf8ByteLength(JSON.stringify(response)) < MAX_TRANSCRIPT_SEGMENT_RESPONSE_BYTES;
}

/**
 * Existing subtitle pages are limited by the native host, but enforce the
 * native-messaging frame boundary again before cue text reaches extension
 * memory. This also covers completed transcript cue retrieval used for export.
 */
function isBoundedSubtitleCueResponse(
  requestId: string | undefined,
  jobId: string,
  cues: readonly NativeSubtitleCue[],
  nextCursor: number | undefined
): boolean {
  const response: Record<string, unknown> = {
    response: "subtitle_cues",
    job_id: jobId,
    cues
  };
  if (requestId !== undefined) {
    response.request_id = requestId;
  }
  if (nextCursor !== undefined) {
    response.next_cursor = nextCursor;
  }
  return utf8ByteLength(JSON.stringify(response)) < MAX_SUBTITLE_CUE_RESPONSE_BYTES;
}
