#requires -Version 5.1
[CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'High')]
param(
    [Parameter(Mandatory)]
    [string]$ExtensionId,

    [string]$InstallDirectory = (Join-Path $env:LOCALAPPDATA 'Subtitler\developer\native-messaging')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Import-Module (Join-Path $PSScriptRoot 'native-host-registration.psm1') -Force

$validatedExtensionId = Assert-SubtitlerExtensionId -ExtensionId $ExtensionId
$resolvedInstallDirectory = Resolve-SubtitlerDeveloperInstallDirectory -InstallDirectory $InstallDirectory
$manifestPath = Get-SubtitlerNativeHostManifestPath -InstallDirectory $resolvedInstallDirectory
$hostName = Get-SubtitlerNativeHostName
$registryPath = Get-SubtitlerNativeHostRegistryPath
$registration = Get-SubtitlerNativeHostRegistration

if ($null -eq $registration) {
    Write-Host "No per-user developer registration exists for $hostName. Nothing was removed."
    return
}

$registeredManifestPath = Resolve-SubtitlerLocalPath -Path $registration.ManifestPath
if (-not (Test-SubtitlerPathEqual -Left $registeredManifestPath -Right $manifestPath)) {
    throw "The $hostName registry value does not point to this exact developer-owned manifest. Refusing to remove it."
}

if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) {
    throw "The expected developer manifest is missing. Refusing to remove a stale registration automatically: $manifestPath"
}

# The manifest must be one generated by this developer tool: exact host name,
# exact caller extension origin, exact property set, and a local executable path.
$validateManifestParameters = @{
    ManifestPath = $manifestPath
    ExtensionId  = $validatedExtensionId
}
$null = Test-SubtitlerNativeHostManifest @validateManifestParameters

if ($WhatIfPreference) {
    $null = $PSCmdlet.ShouldProcess($registryPath, "Remove the exact per-user $hostName registration")
    $null = $PSCmdlet.ShouldProcess($manifestPath, 'Remove the validated developer native-host manifest')
    Write-Host "WhatIf validation passed; no registry key, manifest, executable, or directory was removed."
    return
}

if (-not $PSCmdlet.ShouldProcess(
        "$registryPath and $manifestPath",
        "Remove the validated developer registration for $hostName"
    )) {
    return
}

# Revalidate immediately before deletion. A concurrent modification causes the
# operation to fail closed rather than deleting a substituted manifest/key.
$currentRegistration = Get-SubtitlerNativeHostRegistration
if ($null -eq $currentRegistration) {
    throw 'The native-host registration disappeared before removal; no manifest was removed.'
}

$currentRegisteredManifestPath = Resolve-SubtitlerLocalPath -Path $currentRegistration.ManifestPath
if (-not (Test-SubtitlerPathEqual -Left $currentRegisteredManifestPath -Right $manifestPath)) {
    throw 'The native-host registry value changed before removal; no manifest was removed.'
}

$null = Test-SubtitlerNativeHostManifest @validateManifestParameters

# Removing registration first means a failed file deletion leaves at most an
# unreferenced developer manifest; it never leaves Chrome pointing to a file
# that this script has just deleted. The script intentionally never removes the
# executable or its containing directory.
Remove-Item -LiteralPath $registryPath -Force
try {
    [System.IO.File]::Delete($manifestPath)
}
catch {
    throw "The registry registration was removed, but the validated manifest could not be deleted: $manifestPath"
}

if ([System.IO.File]::Exists($manifestPath)) {
    throw "The registry registration was removed, but the validated manifest still exists: $manifestPath"
}

Write-Host "Removed the developer registration and manifest for $hostName."
Write-Host 'The executable and developer directory were intentionally retained.'
