use serde::{Deserialize, Serialize};
use std::fmt;
use thiserror::Error;
use uuid::Uuid;

/// A job identifier generated by the native host. It is transparent on the
/// wire so protocol messages use a normal UUID string.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct JobId(pub Uuid);

impl JobId {
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }
}

impl Default for JobId {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for JobId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

/// The operation a Subtitler job performs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum JobKind {
    FullTranscript,
    SubtitleGeneration,
}

/// A source requested by the extension. A browser page is intentionally not a
/// promise that the native host can reuse browser authentication: that requires
/// explicit browser-mediated acquisition later in the pipeline.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum MediaSource {
    Page { page_url: String },
    DirectUrl { media_url: String },
    LocalFile { path: String },
}

impl MediaSource {
    pub fn location(&self) -> &str {
        match self {
            Self::Page { page_url } => page_url,
            Self::DirectUrl { media_url } => media_url,
            Self::LocalFile { path } => path,
        }
    }
}

/// Caption metadata discovered by the extension. The actual caption payload is
/// deliberately not part of the normal native-messaging handshake.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct CaptionTrack {
    pub language: String,
    #[serde(default)]
    pub label: Option<String>,
    #[serde(default)]
    pub reliable: bool,
    #[serde(default)]
    pub source_url: Option<String>,
}

/// Hints supplied by the extension after page inspection. They are advisory;
/// every native acquisition implementation still has to enforce its own
/// policy before it reads media.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct MediaAccessHints {
    #[serde(default)]
    pub duration_ms: Option<u64>,
    #[serde(default)]
    pub existing_captions: Vec<CaptionTrack>,
    #[serde(default)]
    pub drm_detected: bool,
    #[serde(default)]
    pub requires_browser_session: bool,
    #[serde(default)]
    pub platform: Option<String>,
}

/// Media information sufficient for preflight. It never includes cookies,
/// authorization headers, or other browser secrets.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct MediaRequest {
    pub source: MediaSource,
    #[serde(default)]
    pub hints: MediaAccessHints,
}

/// A caller's local/cloud preference. Cloud processing is opt-in; the native
/// host must not turn this preference into an upload on its own.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProcessingPreference {
    #[default]
    LocalOnly,
    LocalPreferred,
    CloudExplicitlyApproved,
}

/// User-facing but optional job tuning. Normal extension UI can omit this and
/// receive the privacy-preserving defaults.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct JobSettings {
    #[serde(default)]
    pub force_generate_with_subtitler: bool,
    #[serde(default)]
    pub processing_preference: ProcessingPreference,
    #[serde(default)]
    pub speaker_diarization: bool,
    #[serde(default)]
    pub preferred_subtitle_buffer_ms: Option<u64>,
    /// A bounded snapshot of the active player when a generated-subtitle job
    /// starts. This is timeline metadata only: it never contains a media URL,
    /// caption text, cookies, or browser credentials. Supplying it lets the
    /// first scheduled window begin near a user who opened the popup after
    /// seeking, instead of briefly doing unnecessary work from zero.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub initial_playback: Option<InitialPlayback>,
}

impl Default for JobSettings {
    fn default() -> Self {
        Self {
            force_generate_with_subtitler: false,
            processing_preference: ProcessingPreference::LocalOnly,
            speaker_diarization: false,
            preferred_subtitle_buffer_ms: None,
            initial_playback: None,
        }
    }
}

/// Timeline-only state supplied with a generated-subtitle start request.
/// Playback rate intentionally uses the same integer wire representation as
/// `PlaybackUpdate`; it avoids trusting floating point values from a page.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct InitialPlayback {
    pub position_ms: u64,
    pub playback_rate_milli: u16,
    pub is_paused: bool,
}

/// The complete request for a long-running native task.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct JobSpec {
    /// An optional caller correlation value. Native-host generated IDs remain
    /// authoritative and are returned in `JobStatus`.
    #[serde(default)]
    pub client_job_id: Option<String>,
    pub kind: JobKind,
    pub media: MediaRequest,
    #[serde(default)]
    pub settings: JobSettings,
}

/// Which safe acquisition path was selected during preflight.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AcquisitionStrategy {
    ExistingCaptions,
    DirectMedia,
    BrowserMediated,
    LocalFile,
    Unsupported,
}

/// A redacted acquisition decision suitable for returning to the extension.
/// Do not add media URLs, signed query strings, or credentials to this type.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct AcquisitionReport {
    pub strategy: AcquisitionStrategy,
    pub summary: String,
    pub requires_user_action: bool,
}

/// Monotonic, time-based progress for transcript and subtitle jobs.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct JobProgress {
    #[serde(default)]
    pub media_duration_ms: Option<u64>,
    #[serde(default)]
    pub processed_ms: u64,
    #[serde(default)]
    pub subtitle_buffer_ahead_ms: Option<u64>,
    /// The most specific locally observed phase. It is operational metadata
    /// only: it never includes a source URL, file path, credential, or text.
    #[serde(default)]
    pub phase: Option<JobPhase>,
    /// UTC Unix time in milliseconds for the last real local activity. This
    /// is intentionally distinct from a browser polling time so a watchdog
    /// can detect a genuinely silent worker without imposing a whole-job cap.
    #[serde(default)]
    pub last_progress_at_ms: Option<u64>,
    #[serde(default)]
    pub media_bytes_processed: u64,
    #[serde(default)]
    pub audio_seconds_decoded_ms: u64,
    #[serde(default)]
    pub audio_seconds_transcribed_ms: u64,
    #[serde(default)]
    pub completed_intervals: u32,
    #[serde(default)]
    pub worker_pid: Option<u32>,
    #[serde(default)]
    pub worker_status: WorkerStatus,
}

impl JobProgress {
    pub fn percent(&self) -> Option<u8> {
        let duration = self.media_duration_ms?;
        if duration == 0 {
            return Some(100);
        }

        let percent = self.processed_ms.saturating_mul(100) / duration;
        Some(percent.min(100) as u8)
    }
}

/// Stable job lifecycle states. `Failed` carries an understandable
/// `JobFailure`, not an implementation-specific error number.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum JobState {
    Queued,
    Discovering,
    Acquiring,
    Processing,
    Completed,
    Cancelled,
    /// A prior native process stopped while this job was non-terminal. The
    /// browser can safely retry it, but must not claim that it is still doing
    /// local work.
    Stale,
    Failed,
}

impl JobState {
    pub fn is_terminal(self) -> bool {
        matches!(
            self,
            Self::Completed | Self::Cancelled | Self::Stale | Self::Failed
        )
    }
}

/// Fine-grained job lifecycle labels used for local progress and recovery.
/// They deliberately describe work, not the source media or its contents.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum JobPhase {
    #[default]
    Resolving,
    Acquiring,
    Decoding,
    Transcribing,
    Segmenting,
    Finalizing,
    Complete,
    Failed,
    Cancelled,
    Stale,
}

/// Coarse child/worker state. `worker_pid` is populated only where the local
/// backend can observe one; no process command line is ever persisted.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WorkerStatus {
    #[default]
    NotStarted,
    Active,
    Waiting,
    Finished,
    Unavailable,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum JobFailureCode {
    UnsupportedMedia,
    ProtectedMedia,
    AuthenticationRequired,
    NativeCompanionUnavailable,
    NetworkFailure,
    InsufficientStorage,
    InsufficientMemory,
    ModelUnavailable,
    MediaDecodeFailure,
    EngineFailure,
    Cancelled,
    InvalidRequest,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct JobFailure {
    pub code: JobFailureCode,
    pub message: String,
    #[serde(default)]
    pub retryable: bool,
}

/// Status records are compact enough for periodic native-messaging polling.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct JobStatus {
    pub job_id: JobId,
    pub kind: JobKind,
    pub state: JobState,
    pub progress: JobProgress,
    #[serde(default)]
    pub message: Option<String>,
    #[serde(default)]
    pub failure: Option<JobFailure>,
}

impl JobStatus {
    pub fn queued(job_id: JobId, kind: JobKind, duration_ms: Option<u64>) -> Self {
        Self {
            job_id,
            kind,
            state: JobState::Queued,
            progress: JobProgress {
                media_duration_ms: duration_ms,
                phase: Some(JobPhase::Resolving),
                worker_status: WorkerStatus::NotStarted,
                ..JobProgress::default()
            },
            message: Some("Queued for local processing.".to_owned()),
            failure: None,
        }
    }
}

/// A timestamp range used by words, transcript segments, and subtitle cues.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TimeRange {
    pub start_ms: u64,
    pub end_ms: u64,
}

impl TimeRange {
    pub fn new(start_ms: u64, end_ms: u64) -> Result<Self, TimestampError> {
        if end_ms < start_ms {
            return Err(TimestampError::EndBeforeStart { start_ms, end_ms });
        }
        Ok(Self { start_ms, end_ms })
    }

    pub fn duration_ms(self) -> u64 {
        self.end_ms.saturating_sub(self.start_ms)
    }
}

#[derive(Clone, Debug, Error, PartialEq, Eq)]
pub enum TimestampError {
    #[error("timestamp end ({end_ms} ms) precedes start ({start_ms} ms)")]
    EndBeforeStart { start_ms: u64, end_ms: u64 },
}

/// A word-level ASR timestamp. Speaker labels can be source metadata or a
/// lightweight diarization result; they are never inferred by a general LLM.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct WordTimestamp {
    pub text: String,
    pub timing: TimeRange,
    #[serde(default)]
    pub speaker: Option<String>,
}

impl WordTimestamp {
    pub fn validate(&self) -> Result<(), TranscriptValidationError> {
        if self.text.trim().is_empty() {
            return Err(TranscriptValidationError::EmptyWord);
        }
        if self.timing.end_ms < self.timing.start_ms {
            return Err(TranscriptValidationError::InvalidTiming);
        }
        Ok(())
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TranscriptSegment {
    pub timing: TimeRange,
    pub text: String,
    #[serde(default)]
    pub speaker: Option<String>,
    #[serde(default)]
    pub words: Vec<WordTimestamp>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Transcript {
    pub language: String,
    #[serde(default)]
    pub translated_from: Option<String>,
    pub segments: Vec<TranscriptSegment>,
}

#[derive(Clone, Debug, Error, PartialEq, Eq)]
pub enum TranscriptValidationError {
    #[error("a word must contain visible text")]
    EmptyWord,
    #[error("a word timestamp is invalid")]
    InvalidTiming,
    #[error("word timestamps must be ordered")]
    OutOfOrderWord,
}

impl Transcript {
    pub fn validate(&self) -> Result<(), TranscriptValidationError> {
        let mut previous_end = 0;
        for segment in &self.segments {
            for word in &segment.words {
                word.validate()?;
                if word.timing.start_ms < previous_end {
                    return Err(TranscriptValidationError::OutOfOrderWord);
                }
                previous_end = word.timing.end_ms;
            }
        }
        Ok(())
    }
}

/// A renderer-ready subtitle cue. `lines` is deliberately structured so the
/// overlay can preserve line wrapping selected by the segmenter.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SubtitleCue {
    pub timing: TimeRange,
    pub lines: Vec<String>,
    #[serde(default)]
    pub speaker: Option<String>,
}

impl SubtitleCue {
    pub fn text(&self) -> String {
        self.lines.join(" ")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn progress_is_capped_at_one_hundred_percent() {
        let progress = JobProgress {
            media_duration_ms: Some(1_000),
            processed_ms: 1_250,
            subtitle_buffer_ahead_ms: None,
            ..JobProgress::default()
        };
        assert_eq!(progress.percent(), Some(100));
    }

    #[test]
    fn timestamp_range_rejects_reverse_ranges() {
        let error = TimeRange::new(20, 10).unwrap_err();
        assert!(matches!(error, TimestampError::EndBeforeStart { .. }));
    }
}
